[project]
name = "fast-api-beyond-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "fastapi[standard]",
    "mypy>=1.16.0",
]
